### PR TITLE
Finished supply page for html and css

### PR DESCRIPTION
**Pull request by Solis07**

### CODE REVIEW

**Review by Bwilliams-88 — APPROVED** [review]
Looks good

**Comment by whitewolfZen** [comment]
Looks good

**Review by whitewolfZen — COMMENTED** [review]
Test

**Review by aceiln — COMMENTED** [review]
neat

**Review by astand02 — COMMENTED** [review]
good job guys!!

**Review by aceiln — APPROVED** [review]
neat

**Review by astand02 — APPROVED** [review]
good job guys!

**Pull request merged**
